server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: skpatelsk344@gmail.com
    password: alih gkvu zjzq lulp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      JournalAppDemo:
        JournalApp: TRACE

