spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER_HOST}/?retryWrites=true&w=majority&appName=${MONGO_APP_NAME}
      database: journaldb
      auto-index-creation: true
